# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd1f75951be4bf4f48a05d0d2d6ffe1b188487f008eb5ae304dd59d1599cba89dc7a7a8e847e0ef836be4bb970d66e5ba7c9e34465cdb17584897c97d17306bc

test:
  secret_key_base: a8e5c60fc80bace279444fca03e70bc68de2080d280d5ea85271ce4532c7975c10b137b24cf3ea81de52f9abf215cb8593a9acb47ff2be0e731bb124a6028a3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
